[theme]
primaryColor = "#336633"  # Verde escuro para elementos interativos
backgroundColor = "#c2d5cb"  # Verde claro, tonalidade fosca
secondaryBackgroundColor = "#a8c0a5"  # Verde um pouco mais escuro
textColor = "#222222"  # Cinza escuro para o texto
font = "sans-serif"