[theme]
primaryColor = "#79aec8"  # Azul claro
backgroundColor = "#f0f0f0"  # Branco acinzentado
secondaryBackgroundColor = "#e0e0e0"  # Cinza claro
textColor = "#333333"  # Cinza escuro
font = "sans-serif"