[theme]
primaryColor = "#2e9a40"  
backgroundColor = "#282A36"  # Cinza escuro
secondaryBackgroundColor = "#44475A"  # Cinza um pouco mais claro
textColor = "#F8F8F2"  # Branco quase puro
font = "sans-serif"