[theme]
primaryColor = "#E0E0E0"  # Cinza claro
backgroundColor = "#F5F5F5"  # Branco suave
secondaryBackgroundColor = "#DCDCDC"  # Cinza mais escuro
textColor = "#444444"  # Cinza escuro
font = "sans-serif"